before_install:
- sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- make
deploy:
  provider: releases
  api_key:
    secure: DAAI+exwKOTakE18YFilJ8aum1oim2EL2TKtVdwUOQ2pGtO90tiJYue5oxYmmEVgnXCHGeiS4uJMamSWiBx/VbgHAjlEkN2TPVkR1wXlIV1UfKkt5wMmWVHztWOa97zH6oKa3YhH1xe88gt5HSrMo6V8uHtyaXszkIpJMr6/xT5azYPMmf8Vd/3jwvjKJMTM9GrOlN08oTRnKp7Zpr+f7YdpDiJIRoSxqDKAzFbDoACagY6jcvYyzRIDmp8CIQ5vxqj+sYEkaPgfoLwdJws4yqHBk9M2nWBbjBcj/DhTDycxBHdyKHQiYvCykrLA1e9ubn1TnTQlPf5PGhyIeDmnVf7gyCwGrLjN/PLnP23zu6Y8XLkOdJFAmo5wxCjh1He+RJZ0YrTGUgPw4VbetJSXW8huYKW1OkvcxrvMeEHOIGgrZhc6LTqVr+FqD/B8SnppLqe8H8kqOGTklfT12YkCJuG/bjvdmmaQ0MOkCcoNNpxfRm4YRmzPUUj+3zoV1VkPqzGaNkzBGR+nOBgqlLgDTeWrQira/3GcmbfEVNWasJZJvGdheoeA/usmM68ETkRQGhQydBiQWu5Exxm+Mn0G7Kec5rwkxB65UllsKoQyMD9mOerI82VBIB8sLKgDXir0q9ZGXi53QafaGFYaAgaDwGWKthLNTw+2W19/0bcpPAk=
  file: main.pdf
  skip_cleanup: true
  on:
    tags: true
